# Generated by Django 6.0.6 on 2026-06-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, choices=[('dark', 'Dark'), ('happy', 'Happy'), ('romantic', 'Romantic'), ('aggressive', 'Aggressive'), ('chill', 'Chill'), ('motivational', 'Motivational')], max_length=255)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('preview_file', models.FileField(upload_to='previews/')),
                ('full_file', models.FileField(upload_to='fulltracks/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.genre')),
            ],
        ),
    ]
