# Generated by Django 6.0.6 on 2026-06-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('non_exclusive', 'Non Exclusive'), ('exclusive', 'Exclusive'), ('buyouts', 'Buyouts'), ('free_download', 'Free Download')], default='free_download', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('file_format', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('stems', 'Stems (ZIP)')], default='mp3', max_length=10)),
                ('terms', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='beats.beat')),
            ],
            options={
                'unique_together': {('beat', 'license_type')},
            },
        ),
    ]
